FROM node:19 AS build


WORKDIR /app


COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:19-alpine
WORKDIR /app

RUN npm install -g serve
COPY --from=build /app/dist ./dist
EXPOSE 3001


CMD ["node", "dist/src/index.js"]
