FROM node:19 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:19-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=build /app/dist ./ 

RUN mkdir -p /app/uploads/images /app/uploads/videos

EXPOSE 3001
CMD ["node", "index.js"] 